export const SETTINGS_VERSION = __WHTV_VERSION__;
export const SETTINGS_REPOSITORY_URL = __WHTV_REPOSITORY_URL__;
export const SETTINGS_CHANGELOG_URL = `${SETTINGS_REPOSITORY_URL}/blob/main/CHANGELOG.md`;
